version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  odoo:
    build: .
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
      DATABASE: odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: ["odoo", "--config=/etc/odoo/odoo.conf", "--update=workplace_arm"]

volumes:
  odoo-db-data:
  odoo-web-data:
